
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.hashcatHitman]
url = "https://raw.githubusercontent.com/hashcatHitman/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"
