
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.hashcatHitman]
url = "https://raw.githubusercontent.com/hashcatHitman/supply-chain/main/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[[exemptions.aho-corasick]]
version = "1.1.4"
criteria = "safe-to-deploy"

[[exemptions.memchr]]
version = "2.7.6"
criteria = "safe-to-deploy"

[[exemptions.regex]]
version = "1.12.2"
criteria = "safe-to-deploy"

[[exemptions.regex-automata]]
version = "0.4.13"
criteria = "safe-to-deploy"
